theme: jekyll-theme-cayman
title: "The World Of Folk & Fairy Tales"
collections:
  tales:
    output: true
    layout: tales
  bibliographies:
    output: true
    layout: bibliographies
  category:
    output: true
